// Code generated by thriftgo (0.4.1). DO NOT EDIT.

package share_my_status

import (
	"github.com/apache/thrift/lib/go/thrift"
	"share-my-status/api/model/share_my_status/cover"
	"share-my-status/api/model/share_my_status/state"
	"share-my-status/api/model/share_my_status/stats"
	"share-my-status/api/model/share_my_status/websocket"
)

// 通过继承的方式组织各个服务
type StateService interface {
	state.StateService
}

type StateServiceClient struct {
	*state.StateServiceClient
}

func NewStateServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *StateServiceClient {
	return &StateServiceClient{
		StateServiceClient: state.NewStateServiceClientFactory(t, f),
	}
}

func NewStateServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *StateServiceClient {
	return &StateServiceClient{
		StateServiceClient: state.NewStateServiceClientProtocol(t, iprot, oprot),
	}
}

func NewStateServiceClient(c thrift.TClient) *StateServiceClient {
	return &StateServiceClient{
		StateServiceClient: state.NewStateServiceClient(c),
	}
}

type StatsService interface {
	stats.StatsService
}

type StatsServiceClient struct {
	*stats.StatsServiceClient
}

func NewStatsServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *StatsServiceClient {
	return &StatsServiceClient{
		StatsServiceClient: stats.NewStatsServiceClientFactory(t, f),
	}
}

func NewStatsServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *StatsServiceClient {
	return &StatsServiceClient{
		StatsServiceClient: stats.NewStatsServiceClientProtocol(t, iprot, oprot),
	}
}

func NewStatsServiceClient(c thrift.TClient) *StatsServiceClient {
	return &StatsServiceClient{
		StatsServiceClient: stats.NewStatsServiceClient(c),
	}
}

type CoverService interface {
	cover.CoverService
}

type CoverServiceClient struct {
	*cover.CoverServiceClient
}

func NewCoverServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *CoverServiceClient {
	return &CoverServiceClient{
		CoverServiceClient: cover.NewCoverServiceClientFactory(t, f),
	}
}

func NewCoverServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *CoverServiceClient {
	return &CoverServiceClient{
		CoverServiceClient: cover.NewCoverServiceClientProtocol(t, iprot, oprot),
	}
}

func NewCoverServiceClient(c thrift.TClient) *CoverServiceClient {
	return &CoverServiceClient{
		CoverServiceClient: cover.NewCoverServiceClient(c),
	}
}

type WebSocketService interface {
	websocket.WebSocketService
}

type WebSocketServiceClient struct {
	*websocket.WebSocketServiceClient
}

func NewWebSocketServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *WebSocketServiceClient {
	return &WebSocketServiceClient{
		WebSocketServiceClient: websocket.NewWebSocketServiceClientFactory(t, f),
	}
}

func NewWebSocketServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *WebSocketServiceClient {
	return &WebSocketServiceClient{
		WebSocketServiceClient: websocket.NewWebSocketServiceClientProtocol(t, iprot, oprot),
	}
}

func NewWebSocketServiceClient(c thrift.TClient) *WebSocketServiceClient {
	return &WebSocketServiceClient{
		WebSocketServiceClient: websocket.NewWebSocketServiceClient(c),
	}
}

type StateServiceProcessor struct {
	*state.StateServiceProcessor
}

func NewStateServiceProcessor(handler StateService) *StateServiceProcessor {
	self := &StateServiceProcessor{state.NewStateServiceProcessor(handler)}
	return self
}

type StatsServiceProcessor struct {
	*stats.StatsServiceProcessor
}

func NewStatsServiceProcessor(handler StatsService) *StatsServiceProcessor {
	self := &StatsServiceProcessor{stats.NewStatsServiceProcessor(handler)}
	return self
}

type CoverServiceProcessor struct {
	*cover.CoverServiceProcessor
}

func NewCoverServiceProcessor(handler CoverService) *CoverServiceProcessor {
	self := &CoverServiceProcessor{cover.NewCoverServiceProcessor(handler)}
	return self
}

type WebSocketServiceProcessor struct {
	*websocket.WebSocketServiceProcessor
}

func NewWebSocketServiceProcessor(handler WebSocketService) *WebSocketServiceProcessor {
	self := &WebSocketServiceProcessor{websocket.NewWebSocketServiceProcessor(handler)}
	return self
}
