// Code generated by hertz generator.

package main

import (
	"share-my-status/api/handler/legacy"
	share_my_status "share-my-status/api/handler/share_my_status"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/api/v1/render", share_my_status.RenderPreview)

	// 注册旧版兼容接口
	r.POST("/api/status/v1", legacy.UploadStatus)
	r.GET("/link", legacy.HandleLink)
}
