apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: share-my-status
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_DATABASE
              value: "share_my_status"
            - name: MYSQL_USER
              value: "share_user"
            - name: MYSQL_PASSWORD
              value: "share_password_change_me"
            - name: MYSQL_ROOT_PASSWORD
              value: "root_password_change_me"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          emptyDir: {}