// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infra

import (
	"github.com/google/wire"
	lark2 "github.com/larksuite/oapi-sdk-go/v3"
	ws2 "github.com/larksuite/oapi-sdk-go/v3/ws"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
	"share-my-status/domain/cover"
	"share-my-status/domain/state"
	"share-my-status/domain/stats"
	"share-my-status/domain/user"
	"share-my-status/infra/cache"
	"share-my-status/infra/config"
	"share-my-status/infra/database"
	"share-my-status/infra/lark"
	"share-my-status/infra/scheduler"
	"share-my-status/infra/ws"
)

// Injectors from wire.go:

// InitializeApp 初始化应用依赖
func InitializeApp() (*AppDependencies, error) {
	configConfig, err := config.Init()
	if err != nil {
		return nil, err
	}
	db, err := database.Init(configConfig)
	if err != nil {
		return nil, err
	}
	client, err := cache.Init(configConfig)
	if err != nil {
		return nil, err
	}
	larkClient, err := lark.InitLarkClient(configConfig)
	if err != nil {
		return nil, err
	}
	userService := user.NewUserService(db, client)
	eventHandler := lark.NewEventHandler(userService, db, larkClient)
	eventDispatcher, err := lark.InitEventDispatcher(configConfig, eventHandler)
	if err != nil {
		return nil, err
	}
	wsClient, err := lark.InitWsClient(configConfig, eventDispatcher)
	if err != nil {
		return nil, err
	}
	distributedWebSocketService := ws.InitDistributedWebSocketService(client, db)
	schedulerScheduler := scheduler.NewScheduler(db, configConfig)
	coverService := cover.NewCoverService(db, client)
	statsService := stats.NewStatsService(db, client)
	stateService := state.NewStateService(db, client, distributedWebSocketService, userService)
	appDependencies := &AppDependencies{
		Config:       configConfig,
		DB:           db,
		RedisClient:  client,
		LarkClient:   larkClient,
		LarkWSClient: wsClient,
		WSClient:     distributedWebSocketService,
		Scheduler:    schedulerScheduler,
		CoverService: coverService,
		UserService:  userService,
		StatsService: statsService,
		StateService: stateService,
	}
	return appDependencies, nil
}

// wire.go:

// AppDependencies 应用依赖结构
type AppDependencies struct {
	Config       *config.Config
	DB           *gorm.DB
	RedisClient  *redis.Client
	LarkClient   *lark2.Client
	LarkWSClient *ws2.Client
	WSClient     *ws.DistributedWebSocketService
	Scheduler    *scheduler.Scheduler

	CoverService *cover.CoverService
	UserService  *user.UserService
	StatsService *stats.StatsService
	StateService *state.StateService
}

// ProviderSet 定义所有Provider的集合
var ProviderSet = wire.NewSet(config.Init, database.Init, cache.Init, lark.InitLarkClient, lark.InitWsClient, lark.InitEventDispatcher, lark.NewEventHandler, ws.InitDistributedWebSocketService, cover.NewCoverService, user.NewUserService, stats.NewStatsService, state.NewStateService, scheduler.NewScheduler, wire.Struct(new(AppDependencies), "*"))

var GlobalAppDependencies *AppDependencies

func GetGlobalAppDependencies() *AppDependencies {
	return GlobalAppDependencies
}
