apiVersion: v2
name: share-my-status
description: Real-time personal status sharing platform (Go backend + React frontend)
type: application
version: 1.0.501-b.1.0.5.1.f.1.0.5.1
appVersion: "backend=1.0.5-1,frontend=1.0.5-1"

dependencies:
  - name: mysql
    version: 14.0.x
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: redis
    version: 25.5.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
