apiVersion: v2
name: share-my-status
description: Real-time personal status sharing platform (Go backend + React frontend)
type: application
version: 1.0.504-b.1.0.6.5.f.1.0.5.2
appVersion: "backend=1.0.6-5,frontend=1.0.5-2"

dependencies:
  - name: postgresql
    version: 18.6.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 25.5.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
