// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package providers

import (
	"github.com/google/wire"
	"github.com/larksuite/oapi-sdk-go/v3"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
	"share-my-status/internal/config"
	"share-my-status/internal/service"
)

// Injectors from wire.go:

// InitializeApp 初始化应用依赖
func InitializeApp() (*AppDependencies, error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	db, err := ProvideDatabase(config)
	if err != nil {
		return nil, err
	}
	client, err := ProvideRedis(config)
	if err != nil {
		return nil, err
	}
	larkClient := ProvideLarkClient(config)
	serviceManager := ProvideServiceManager(db, client)
	appDependencies := &AppDependencies{
		Config:         config,
		DB:             db,
		RedisClient:    client,
		LarkClient:     larkClient,
		ServiceManager: serviceManager,
	}
	return appDependencies, nil
}

// wire.go:

// AppDependencies 应用依赖结构
type AppDependencies struct {
	Config         *config.Config
	DB             *gorm.DB
	RedisClient    *redis.Client
	LarkClient     *lark.Client
	ServiceManager *service.ServiceManager
}

// ProviderSet 定义所有Provider的集合
var ProviderSet = wire.NewSet(
	ProvideConfig,
	ProvideDatabase,
	ProvideRedis,
	ProvideLarkClient,
	ProvideServiceManager, wire.Struct(new(AppDependencies), "*"),
)
