{{- if .Values.backend.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "share-my-status.backend.fullname" . }}-env
  labels:
    {{- include "share-my-status.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  {{- range $key, $value := .Values.backend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
