{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "share-my-status.fullname" . }}
  labels:
    {{- include "share-my-status.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .backendPaths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "share-my-status.backend.fullname" $ }}
                port:
                  number: {{ $.Values.backend.service.port }}
          {{- end }}
          {{- range .frontendPaths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "share-my-status.frontend.fullname" $ }}
                port:
                  number: {{ $.Values.frontend.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
