// Code generated by hertz generator.

package share_my_status

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	cover "share-my-status/api/model/share_my_status/cover"
	state "share-my-status/api/model/share_my_status/state"
	stats "share-my-status/api/model/share_my_status/stats"
	websocket "share-my-status/api/model/share_my_status/websocket"
)

// CheckExists .
// @router /v1/cover/exists [GET]
func CheckExists(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cover.CoverExistsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(cover.CoverExistsResponse)

	c.JSON(consts.StatusOK, resp)
}

// Upload .
// @router /v1/cover/upload [POST]
func Upload(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cover.CoverUploadRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(cover.CoverUploadResponse)

	c.JSON(consts.StatusOK, resp)
}

// Get .
// @router /v1/cover/{hash} [GET]
func Get(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cover.CoverGetRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(cover.CoverGetResponse)

	c.JSON(consts.StatusOK, resp)
}

// BatchReport .
// @router /v1/state/report [POST]
func BatchReport(ctx context.Context, c *app.RequestContext) {
	var err error
	var req state.BatchReportRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(state.BatchReportResponse)

	c.JSON(consts.StatusOK, resp)
}

// QueryState .
// @router /v1/state/query [GET]
func QueryState(ctx context.Context, c *app.RequestContext) {
	var err error
	var req state.QueryStateRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(state.QueryStateResponse)

	c.JSON(consts.StatusOK, resp)
}

// QueryStats .
// @router /v1/stats/query [POST]
func QueryStats(ctx context.Context, c *app.RequestContext) {
	var err error
	var req stats.StatsQueryRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(stats.StatsQueryResponse)

	c.JSON(consts.StatusOK, resp)
}

// Connect .
// @router /v1/ws [GET]
func Connect(ctx context.Context, c *app.RequestContext) {
	var err error
	var req websocket.WSConnectRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(websocket.WSConnectResponse)

	c.JSON(consts.StatusOK, resp)
}
