// Code generated by thriftgo (0.4.1). DO NOT EDIT.

package stats

import (
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"share-my-status/api/model/share_my_status/common"
)

// 统计查询请求
type StatsQueryRequest struct {
	Window *common.WindowInfo `thrift:"window,1,required" form:"window,required" json:"window,required" query:"window,required"`
	// ["plays", "unique_tracks", "top_artists", "top_tracks"]
	Metrics []string `thrift:"metrics,2,required" form:"metrics,required" json:"metrics,required" query:"metrics,required"`
	TopN    int32    `thrift:"topN,3,optional" form:"topN" json:"topN,omitempty" query:"topN"`
}

func NewStatsQueryRequest() *StatsQueryRequest {
	return &StatsQueryRequest{

		TopN: 10,
	}
}

func (p *StatsQueryRequest) InitDefault() {
	p.TopN = 10
}

var StatsQueryRequest_Window_DEFAULT *common.WindowInfo

func (p *StatsQueryRequest) GetWindow() (v *common.WindowInfo) {
	if !p.IsSetWindow() {
		return StatsQueryRequest_Window_DEFAULT
	}
	return p.Window
}

func (p *StatsQueryRequest) GetMetrics() (v []string) {
	return p.Metrics
}

var StatsQueryRequest_TopN_DEFAULT int32 = 10

func (p *StatsQueryRequest) GetTopN() (v int32) {
	if !p.IsSetTopN() {
		return StatsQueryRequest_TopN_DEFAULT
	}
	return p.TopN
}

var fieldIDToName_StatsQueryRequest = map[int16]string{
	1: "window",
	2: "metrics",
	3: "topN",
}

func (p *StatsQueryRequest) IsSetWindow() bool {
	return p.Window != nil
}

func (p *StatsQueryRequest) IsSetTopN() bool {
	return p.TopN != StatsQueryRequest_TopN_DEFAULT
}

func (p *StatsQueryRequest) Read(iprot thrift.TProtocol) (err error) {
	var fieldTypeId thrift.TType
	var fieldId int16
	var issetWindow bool = false
	var issetMetrics bool = false

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
				issetWindow = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.LIST {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
				issetMetrics = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	if !issetWindow {
		fieldId = 1
		goto RequiredFieldNotSetError
	}

	if !issetMetrics {
		fieldId = 2
		goto RequiredFieldNotSetError
	}
	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_StatsQueryRequest[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
RequiredFieldNotSetError:
	return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("required field %s is not set", fieldIDToName_StatsQueryRequest[fieldId]))
}

func (p *StatsQueryRequest) ReadField1(iprot thrift.TProtocol) error {
	_field := common.NewWindowInfo()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Window = _field
	return nil
}
func (p *StatsQueryRequest) ReadField2(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return err
	}
	_field := make([]string, 0, size)
	for i := 0; i < size; i++ {

		var _elem string
		if v, err := iprot.ReadString(); err != nil {
			return err
		} else {
			_elem = v
		}

		_field = append(_field, _elem)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return err
	}
	p.Metrics = _field
	return nil
}
func (p *StatsQueryRequest) ReadField3(iprot thrift.TProtocol) error {

	var _field int32
	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		_field = v
	}
	p.TopN = _field
	return nil
}

func (p *StatsQueryRequest) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("StatsQueryRequest"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *StatsQueryRequest) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("window", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Window.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}
func (p *StatsQueryRequest) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("metrics", thrift.LIST, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteListBegin(thrift.STRING, len(p.Metrics)); err != nil {
		return err
	}
	for _, v := range p.Metrics {
		if err := oprot.WriteString(v); err != nil {
			return err
		}
	}
	if err := oprot.WriteListEnd(); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}
func (p *StatsQueryRequest) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetTopN() {
		if err = oprot.WriteFieldBegin("topN", thrift.I32, 3); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI32(p.TopN); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}

func (p *StatsQueryRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StatsQueryRequest(%+v)", *p)

}

// 统计查询响应
type StatsQueryResponse struct {
	Base *common.BaseResponse `thrift:"base,1,required" form:"base,required" json:"base,required" query:"base,required"`
	// 回显实际窗口信息
	Window     *common.WindowInfo   `thrift:"window,2,optional" form:"window" json:"window,omitempty" query:"window"`
	Summary    *common.StatsSummary `thrift:"summary,3,optional" form:"summary" json:"summary,omitempty" query:"summary"`
	TopArtists []*common.TopItem    `thrift:"topArtists,4,optional" form:"topArtists" json:"topArtists,omitempty" query:"topArtists"`
	TopTracks  []*common.TopItem    `thrift:"topTracks,5,optional" form:"topTracks" json:"topTracks,omitempty" query:"topTracks"`
}

func NewStatsQueryResponse() *StatsQueryResponse {
	return &StatsQueryResponse{}
}

func (p *StatsQueryResponse) InitDefault() {
}

var StatsQueryResponse_Base_DEFAULT *common.BaseResponse

func (p *StatsQueryResponse) GetBase() (v *common.BaseResponse) {
	if !p.IsSetBase() {
		return StatsQueryResponse_Base_DEFAULT
	}
	return p.Base
}

var StatsQueryResponse_Window_DEFAULT *common.WindowInfo

func (p *StatsQueryResponse) GetWindow() (v *common.WindowInfo) {
	if !p.IsSetWindow() {
		return StatsQueryResponse_Window_DEFAULT
	}
	return p.Window
}

var StatsQueryResponse_Summary_DEFAULT *common.StatsSummary

func (p *StatsQueryResponse) GetSummary() (v *common.StatsSummary) {
	if !p.IsSetSummary() {
		return StatsQueryResponse_Summary_DEFAULT
	}
	return p.Summary
}

var StatsQueryResponse_TopArtists_DEFAULT []*common.TopItem

func (p *StatsQueryResponse) GetTopArtists() (v []*common.TopItem) {
	if !p.IsSetTopArtists() {
		return StatsQueryResponse_TopArtists_DEFAULT
	}
	return p.TopArtists
}

var StatsQueryResponse_TopTracks_DEFAULT []*common.TopItem

func (p *StatsQueryResponse) GetTopTracks() (v []*common.TopItem) {
	if !p.IsSetTopTracks() {
		return StatsQueryResponse_TopTracks_DEFAULT
	}
	return p.TopTracks
}

var fieldIDToName_StatsQueryResponse = map[int16]string{
	1: "base",
	2: "window",
	3: "summary",
	4: "topArtists",
	5: "topTracks",
}

func (p *StatsQueryResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *StatsQueryResponse) IsSetWindow() bool {
	return p.Window != nil
}

func (p *StatsQueryResponse) IsSetSummary() bool {
	return p.Summary != nil
}

func (p *StatsQueryResponse) IsSetTopArtists() bool {
	return p.TopArtists != nil
}

func (p *StatsQueryResponse) IsSetTopTracks() bool {
	return p.TopTracks != nil
}

func (p *StatsQueryResponse) Read(iprot thrift.TProtocol) (err error) {
	var fieldTypeId thrift.TType
	var fieldId int16
	var issetBase bool = false

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
				issetBase = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 4:
			if fieldTypeId == thrift.LIST {
				if err = p.ReadField4(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 5:
			if fieldTypeId == thrift.LIST {
				if err = p.ReadField5(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	if !issetBase {
		fieldId = 1
		goto RequiredFieldNotSetError
	}
	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_StatsQueryResponse[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
RequiredFieldNotSetError:
	return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("required field %s is not set", fieldIDToName_StatsQueryResponse[fieldId]))
}

func (p *StatsQueryResponse) ReadField1(iprot thrift.TProtocol) error {
	_field := common.NewBaseResponse()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Base = _field
	return nil
}
func (p *StatsQueryResponse) ReadField2(iprot thrift.TProtocol) error {
	_field := common.NewWindowInfo()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Window = _field
	return nil
}
func (p *StatsQueryResponse) ReadField3(iprot thrift.TProtocol) error {
	_field := common.NewStatsSummary()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Summary = _field
	return nil
}
func (p *StatsQueryResponse) ReadField4(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return err
	}
	_field := make([]*common.TopItem, 0, size)
	values := make([]common.TopItem, size)
	for i := 0; i < size; i++ {
		_elem := &values[i]
		_elem.InitDefault()

		if err := _elem.Read(iprot); err != nil {
			return err
		}

		_field = append(_field, _elem)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return err
	}
	p.TopArtists = _field
	return nil
}
func (p *StatsQueryResponse) ReadField5(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return err
	}
	_field := make([]*common.TopItem, 0, size)
	values := make([]common.TopItem, size)
	for i := 0; i < size; i++ {
		_elem := &values[i]
		_elem.InitDefault()

		if err := _elem.Read(iprot); err != nil {
			return err
		}

		_field = append(_field, _elem)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return err
	}
	p.TopTracks = _field
	return nil
}

func (p *StatsQueryResponse) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("StatsQueryResponse"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
		if err = p.writeField4(oprot); err != nil {
			fieldId = 4
			goto WriteFieldError
		}
		if err = p.writeField5(oprot); err != nil {
			fieldId = 5
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *StatsQueryResponse) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("base", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Base.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}
func (p *StatsQueryResponse) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetWindow() {
		if err = oprot.WriteFieldBegin("window", thrift.STRUCT, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Window.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}
func (p *StatsQueryResponse) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetSummary() {
		if err = oprot.WriteFieldBegin("summary", thrift.STRUCT, 3); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Summary.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}
func (p *StatsQueryResponse) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetTopArtists() {
		if err = oprot.WriteFieldBegin("topArtists", thrift.LIST, 4); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteListBegin(thrift.STRUCT, len(p.TopArtists)); err != nil {
			return err
		}
		for _, v := range p.TopArtists {
			if err := v.Write(oprot); err != nil {
				return err
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 end error: ", p), err)
}
func (p *StatsQueryResponse) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetTopTracks() {
		if err = oprot.WriteFieldBegin("topTracks", thrift.LIST, 5); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteListBegin(thrift.STRUCT, len(p.TopTracks)); err != nil {
			return err
		}
		for _, v := range p.TopTracks {
			if err := v.Write(oprot); err != nil {
				return err
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 end error: ", p), err)
}

func (p *StatsQueryResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StatsQueryResponse(%+v)", *p)

}
